main:
  components_repository: "https://github.com/CAMM961001/futbol_bayes"
  project_name: futbol_bayes
  steps: all
datos:
  raw: "datos/raw/futbol.csv"
  cat_raw: "datos/raw/_cat_futbol.info"
  waic: "datos/results/deviance_waic.csv"
modelos:
  dir: "modelos"
  template: "modelos/__template__.stan"
visuals:
  colors:
    verde: "#acce91"
    amarillo: "#ffc125"
    rojo: "#cb4154"
    azul: "#07d8de"
    morado: "#6F5C82"
    naranja: "#d28a19"
    gris: "#bebebe"
    aqua: "#007168"
